### PR TITLE
fix(client): parse Presto JSON response with custom reviver and BigInts

### LINKED ISSUE #24: Number responses lose precision
### Current Behavior

Retrieving a big number like `1234567890123456623` returns a `1234567890123456700`.

### Expected Behavior

Return the exact number without losing precision.

### GitHub Repo

_No response_

### Steps to Reproduce

1. query a Presto instance with this: `SELECT 1234567890123456623`
2. check response

### Additional Information

Related to https://github.com/prestodb/presto/issues/23821

### PR DESCRIPTION
**Pull request by alonsovb**
Fixes #24. For now, this only assumes the JSON.parse [includes the context.source in the reviver callback](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#reviver). This is currently a stage 3 proposal but has very good [browser support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#browser_compatibility).

## Changes

Uses a custom JSON.parse reviver for numbers so that everything uses the BigInt primitive instead of the regular Number which loses precision on bigger values.

## Notes

None

## Screenshots

None

### CODE REVIEW

File: presto-client/src/client.ts [hunk 1]
```diff
@@ -9,6 +9,10 @@ import {
   Table,
 } from './types'
 
+function digitsToBigInt(_: string, value: unknown, { source }: { source: string }) {
+  return /^\d+$/.test(source) ? BigInt(source) : value
```
Comment (yhwang) [inline presto-client/src/client.ts]: would it be cheaper to verify if the `value` is a Number than the RE?

**Review by yhwang — APPROVED** [review]
Thanks for the PR and the changes look good to me.
Just left a minor question.

File: presto-client/src/utils.ts [hunk 2]
```diff
@@ -0,0 +1,39 @@
+/**
+ * Parses a JSON including bigger numbers into BigInts
+ * @param _ Key
+ * @param value Parsed value
+ * @param context Context with source text
+ * @returns Parsed object with BigInts where required
+ */
+export function parseWithBigInts(_: string, value: unknown, { source }: { source: string }) {
```
Comment (yhwang) [inline presto-client/src/utils.ts]: Is it good to check the `arguments.length` here for compatibility? Then, there is no need for the `isJsonParseContextAvailable` function.

Comment (alonsovb) [reply presto-client/src/utils.ts]: The problem is `JSON.parse` always has 2 arguments: the actual text to be parsed, and the Reviver callback.
The difference between the old and newer specification is on how many arguments does JSON.parse pass to that Reviver callback (2 or 3). We can't easily check how many arguments will be there on a runtime callback, as far as I know.

Comment (alonsovb) [reply presto-client/src/utils.ts]: oh, just realized you mean checking for the arguments.length inside the reviver itself, that's a good idea! I'll try that 👍

**Comment by alonsovb** [comment]
I refactored the code to do the compat check in the same function by checking if the context (and context.source) values are non falsy.

The only weird thing that happens is if you try to stringify the query response since now it contains a BigInt which is not serializable by the default JSON.stringify function. You need to write a custom replacer like this:

```typescript
const results = await client.query(`SELECT 1234567890123456623`)
return {
  result: JSON.stringify(results.data, (key, value) => {
    if (typeof value !== 'bigint') return value

    return value.toString()
  }),
}
```

Otherwise you may end up with an error like this:

```
ERROR [ExceptionsHandler] Do not know how to serialize a BigInt
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
```

We could either:
1. Leave it like this (up to users on how to serialize BigInts, a bit more work)
2. Automatically parse into string instead of BigInts (lose ability to do some number operations on them unless customly parsed into BigInts)
3. Some kind of param to decide whether to use 1 or 2 per client or per query.

Any advice @yhwang ?

File: presto-client/src/utils.ts [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+ * and falls back onto the default parsing if not.
+ * See also:
+ * - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#browser_compatibility
+ * - https://github.com/tc39/proposal-json-parse-with-source
+ * @param _ Key
+ * @param value Parsed value
+ * @param context Context with source text
+ * @returns Parsed object with BigInts where required
+ */
+export function parseWithBigInts(_: string, value: unknown, context: { source: string }) {
```
Comment (jorgeramirezamora) [inline presto-client/src/utils.ts]: Can we add test coverage to this?

File: presto-client/src/utils.ts [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+  if (!context) return value // Context is not available, fallback to default parse
+  const { source } = context
+  if (!source) return value // Source is not available, fallback to default parse
+
+  // Ignore non-numbers
+  if (typeof value !== 'number') return value
```
Comment (jorgeramirezamora) [inline presto-client/src/utils.ts]:
```suggestion
  if (typeof value != 'number') return value
```

File: presto-client/src/utils.ts [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+ * - https://github.com/tc39/proposal-json-parse-with-source
+ * @param _ Key
+ * @param value Parsed value
+ * @param context Context with source text
+ * @returns Parsed object with BigInts where required
+ */
+export function parseWithBigInts(_: string, value: unknown, context: { source: string }) {
+  if (!context) return value // Context is not available, fallback to default parse
+  const { source } = context
+  if (!source) return value // Source is not available, fallback to default parse
```
Comment (jorgeramirezamora) [inline presto-client/src/utils.ts]: This can be simplified as:
```suggestion
  if (!context?.source) return value
```

File: apps/nest-server/src/app/app.service.ts [hunk 6]
```diff
@@ -48,7 +48,14 @@ export class AppService {
       const results = await client.query(
         `select returnflag, linestatus, sum(quantity) as sum_qty, sum(extendedprice) as sum_base_price, sum(extendedprice * (1 - discount)) as sum_disc_price, sum(extendedprice * (1 - discount) * (1 + tax)) as sum_charge, avg(quantity) as avg_qty, avg(extendedprice) as avg_price, avg(discount) as avg_disc, count(*) as count_order from lineitem where shipdate <= date '1998-12-01' group by returnflag, linestatus order by returnflag, linestatus`,
       )
-      return { columns: results.columns, rows: results.data }
+      return {
+        columns: results.columns,
+        rows: JSON.stringify(results.data, (key, value) => {
+          if (typeof value !== 'bigint') return value
```
Comment (jorgeramirezamora) [inline apps/nest-server/src/app/app.service.ts]:
```suggestion
          if (typeof value != 'bigint') return value
```

File: apps/nest-server/src/app/app.service.ts [hunk 7]
```diff
@@ -48,7 +48,14 @@ export class AppService {
...
+
+          return value.toString()
```
Comment (jorgeramirezamora) [inline apps/nest-server/src/app/app.service.ts:56]: Can u please add to the README this limitation?

File: .nvmrc [hunk 8]
```diff
@@ -1 +1 @@
-18.17.1
+21.0.0
```
Comment (jorgeramirezamora) [inline .nvmrc]: Can't we go to latest instead?

**Review by jorgeramirezamora — CHANGES_REQUESTED** [review]
Some comments below

File: .nvmrc (hunk 8 above)
Comment (alonsovb) [reply .nvmrc]: moved to latest lts nodejs release

File: apps/nest-server/src/app/app.service.ts (hunk 7 above)
Comment (alonsovb) [reply apps/nest-server/src/app/app.service.ts:56]: already did

**Comment by yhwang** [comment]
@alonsovb per your question. My 2 cents:
We should provide APIs like the [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) object. To get the output in text form, use response.text() API, to get the output in JSON form, use response.json() API. In our case, we should provide similar APIs, one for raw data or text, the other for the `PrestoQuery` which has been parsed and converted to BigInt if needed. This would prevent users from getting the parsed data and then stringifying it.

However, this requires API changes. We should document the limitation like what you did now and create an issue to track this and discuss the proper solution there. Your option 2 is also doable and no API change.

File: presto-client/src/utils.ts (hunk 3 above)
Comment (alonsovb) [reply presto-client/src/utils.ts]: added

**Comment by alonsovb** [comment]
Okay, just finished adding some initial unit tests. Let me know if anything else may be needed cc @yhwang @jorgeramirezamora 

Per @yhwang , I created this issue to discuss more about a potential API change for the Client's response object:
https://github.com/prestodb/presto-js-client/issues/26

Thanks everyone!

File: presto-client/src/utils.spec.ts [hunk 9]
```diff
@@ -0,0 +1,38 @@
+import { parseWithBigInts } from './utils'
+
+describe('parse big ints', () => {
```
Comment (jorgeramirezamora) [inline presto-client/src/utils.spec.ts:3]: ❤️

File: presto-client/src/utils.ts [hunk 10]
```diff
@@ -0,0 +1,27 @@
...
+ * and falls back onto the default parsing if not.
+ * See also:
+ * - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#browser_compatibility
+ * - https://github.com/tc39/proposal-json-parse-with-source
+ * @param _ Key
+ * @param value Parsed value
+ * @param context Context with source text
+ * @returns Parsed object with BigInts where required
+ */
+export function parseWithBigInts(_: string, value: unknown, context: { source: string } | undefined) {
```
Comment (jorgeramirezamora) [inline presto-client/src/utils.ts:13]: 🤯

**Review by jorgeramirezamora — APPROVED** [review]
👏🏼

**Review by yhwang — APPROVED** [review]
